/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/NotificationBanner`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/maps`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/places/CategoryTabs`; params?: Router.UnknownInputParams; } | { pathname: `/places/MapComponent`; params?: Router.UnknownInputParams; } | { pathname: `/places/NavigationHeader`; params?: Router.UnknownInputParams; } | { pathname: `/places/PlacesList`; params?: Router.UnknownInputParams; } | { pathname: `/places/PlacesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/places/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/places/Toolbar`; params?: Router.UnknownInputParams; } | { pathname: `/places/types/MapTypes`; params?: Router.UnknownInputParams; } | { pathname: `/places/types/PlaceTypes`; params?: Router.UnknownInputParams; } | { pathname: `/places/types/UserInterfaceStyle`; params?: Router.UnknownInputParams; } | { pathname: `/utils/audio/declarations`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/NotificationBanner`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/maps`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/places/CategoryTabs`; params?: Router.UnknownOutputParams; } | { pathname: `/places/MapComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/places/NavigationHeader`; params?: Router.UnknownOutputParams; } | { pathname: `/places/PlacesList`; params?: Router.UnknownOutputParams; } | { pathname: `/places/PlacesScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/places/SearchBar`; params?: Router.UnknownOutputParams; } | { pathname: `/places/Toolbar`; params?: Router.UnknownOutputParams; } | { pathname: `/places/types/MapTypes`; params?: Router.UnknownOutputParams; } | { pathname: `/places/types/PlaceTypes`; params?: Router.UnknownOutputParams; } | { pathname: `/places/types/UserInterfaceStyle`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/audio/declarations`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/NotificationBanner${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/maps${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/places/CategoryTabs${`?${string}` | `#${string}` | ''}` | `/places/MapComponent${`?${string}` | `#${string}` | ''}` | `/places/NavigationHeader${`?${string}` | `#${string}` | ''}` | `/places/PlacesList${`?${string}` | `#${string}` | ''}` | `/places/PlacesScreen${`?${string}` | `#${string}` | ''}` | `/places/SearchBar${`?${string}` | `#${string}` | ''}` | `/places/Toolbar${`?${string}` | `#${string}` | ''}` | `/places/types/MapTypes${`?${string}` | `#${string}` | ''}` | `/places/types/PlaceTypes${`?${string}` | `#${string}` | ''}` | `/places/types/UserInterfaceStyle${`?${string}` | `#${string}` | ''}` | `/utils/audio/declarations${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/NotificationBanner`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/maps`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/places/CategoryTabs`; params?: Router.UnknownInputParams; } | { pathname: `/places/MapComponent`; params?: Router.UnknownInputParams; } | { pathname: `/places/NavigationHeader`; params?: Router.UnknownInputParams; } | { pathname: `/places/PlacesList`; params?: Router.UnknownInputParams; } | { pathname: `/places/PlacesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/places/SearchBar`; params?: Router.UnknownInputParams; } | { pathname: `/places/Toolbar`; params?: Router.UnknownInputParams; } | { pathname: `/places/types/MapTypes`; params?: Router.UnknownInputParams; } | { pathname: `/places/types/PlaceTypes`; params?: Router.UnknownInputParams; } | { pathname: `/places/types/UserInterfaceStyle`; params?: Router.UnknownInputParams; } | { pathname: `/utils/audio/declarations`; params?: Router.UnknownInputParams; };
    }
  }
}
